insert into cars (id, make, model, year, fuel_type, transmission, owners) values (1, 'Chevrolet', 'Corvette', 2020, 'Electric', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (2, 'BMW', 'Z3', 2021, 'Electric', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (3, 'Mazda', '626', 2021, 'Electric', 'Manual', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (4, 'Ford', 'Escape', 2020, 'Electric', 'CVT', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (5, 'Chevrolet', '3500', 2019, 'Diesel', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (6, 'Honda', 'CR-V', 2018, 'Diesel', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (7, 'Honda', 'Accord', 2020, 'Gasoline', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (8, 'Land Rover', 'Discovery', 2019, 'Electric', 'CVT', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (9, 'Toyota', 'Land Cruiser', 2019, 'Gasoline', 'Automatic', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (10, 'Ford', 'Mustang', 2019, 'Gasoline', 'CVT', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (11, 'Hyundai', 'Elantra', 2022, 'Electric', 'Manual', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (12, 'Chevrolet', 'Caprice', 2022, 'Diesel', 'Automatic', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (13, 'Mercury', 'Mariner', 2022, 'Diesel', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (14, 'Pontiac', 'Firefly', 2019, 'Gasoline', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (15, 'Nissan', 'Pathfinder', 2020, 'Gasoline', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (16, 'Dodge', 'Grand Caravan', 2018, 'Gasoline', 'Manual', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (17, 'Volkswagen', 'Jetta', 2018, 'Diesel', 'Automatic', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (18, 'Acura', 'CL', 2019, 'Electric', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (19, 'Suzuki', 'XL7', 2019, 'Gasoline', 'Manual', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (20, 'Acura', 'Vigor', 2020, 'Electric', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (21, 'Mercury', 'Sable', 2021, 'Diesel', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (22, 'Subaru', 'Legacy', 2020, 'Gasoline', 'CVT', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (23, 'Land Rover', 'LR2', 2020, 'Electric', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (24, 'Ford', 'Expedition EL', 2018, 'Gasoline', 'CVT', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (25, 'GMC', 'Yukon', 2022, 'Electric', 'CVT', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (26, 'Nissan', 'Murano', 2019, 'Electric', 'CVT', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (27, 'Dodge', 'Viper', 2021, 'Electric', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (28, 'Mercury', 'Sable', 2019, 'Electric', 'CVT', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (29, 'Ford', 'Taurus X', 2020, 'Electric', 'Automatic', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (30, 'Mercedes-Benz', 'M-Class', 2019, 'Diesel', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (31, 'Mercedes-Benz', 'SLR McLaren', 2018, 'Gasoline', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (32, 'Ford', 'C-MAX Hybrid', 2018, 'Gasoline', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (33, 'Mercury', 'Mystique', 2021, 'Gasoline', 'CVT', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (34, 'Cadillac', 'XLR', 2021, 'Gasoline', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (35, 'Ford', 'Windstar', 2021, 'Electric', 'CVT', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (36, 'GMC', 'Savana 2500', 2022, 'Electric', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (37, 'Chrysler', 'Sebring', 2020, 'Electric', 'Automatic', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (38, 'Ford', 'F250', 2018, 'Electric', 'Automatic', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (39, 'Mercedes-Benz', 'C-Class', 2020, 'Diesel', 'Manual', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (40, 'Lamborghini', 'Countach', 2022, 'Electric', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (41, 'Acura', 'RL', 2018, 'Electric', 'CVT', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (42, 'Chevrolet', 'Express 3500', 2019, 'Electric', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (43, 'Chevrolet', 'Monte Carlo', 2019, 'Diesel', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (44, 'Infiniti', 'I', 2021, 'Gasoline', 'Manual', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (45, 'Chevrolet', 'Cavalier', 2020, 'Diesel', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (46, 'Lotus', 'Esprit', 2019, 'Diesel', 'CVT', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (47, 'Volvo', 'V50', 2021, 'Diesel', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (48, 'Saab', '9-3', 2019, 'Gasoline', 'Manual', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (49, 'Ford', 'Windstar', 2022, 'Diesel', 'CVT', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (50, 'Mercury', 'Tracer', 2018, 'Electric', 'Automatic', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (51, 'Mercury', 'Topaz', 2021, 'Electric', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (52, 'Eagle', 'Summit', 2021, 'Electric', 'CVT', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (53, 'Chevrolet', 'Silverado 1500', 2018, 'Diesel', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (54, 'Jeep', 'Wrangler', 2018, 'Gasoline', 'Manual', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (55, 'Cadillac', 'Eldorado', 2021, 'Electric', 'Automatic', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (56, 'Geo', 'Prizm', 2018, 'Gasoline', 'CVT', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (57, 'Nissan', 'Xterra', 2020, 'Electric', 'CVT', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (58, 'Jaguar', 'XK', 2020, 'Diesel', 'Manual', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (59, 'Buick', 'Park Avenue', 2018, 'Gasoline', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (60, 'Ford', 'Expedition', 2018, 'Electric', 'Automatic', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (61, 'Aston Martin', 'DBS', 2021, 'Gasoline', 'Manual', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (62, 'Honda', 'Accord', 2020, 'Gasoline', 'CVT', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (63, 'BMW', '3 Series', 2019, 'Gasoline', 'CVT', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (64, 'Isuzu', 'Stylus', 2022, 'Gasoline', 'Automatic', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (65, 'Hummer', 'H1', 2022, 'Electric', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (66, 'Infiniti', 'M', 2018, 'Gasoline', 'Manual', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (67, 'Ford', 'Ranger', 2021, 'Gasoline', 'CVT', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (68, 'Audi', 'A8', 2018, 'Diesel', 'CVT', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (69, 'Toyota', 'Yaris', 2022, 'Diesel', 'CVT', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (70, 'Chrysler', '300M', 2022, 'Electric', 'Manual', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (71, 'Ford', 'Mustang', 2022, 'Gasoline', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (72, 'Volvo', '240', 2021, 'Electric', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (73, 'Suzuki', 'SX4', 2020, 'Electric', 'Manual', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (74, 'Mitsubishi', 'Pajero', 2021, 'Gasoline', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (75, 'Jaguar', 'XK', 2022, 'Electric', 'Manual', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (76, 'Mazda', '626', 2021, 'Diesel', 'Automatic', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (77, 'Volkswagen', 'Jetta', 2021, 'Gasoline', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (78, 'Ford', 'F150', 2021, 'Gasoline', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (79, 'Mercedes-Benz', 'S-Class', 2022, 'Electric', 'CVT', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (80, 'Nissan', 'Sentra', 2020, 'Gasoline', 'CVT', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (81, 'Pontiac', '6000', 2020, 'Diesel', 'CVT', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (82, 'Toyota', 'Corolla', 2018, 'Electric', 'Manual', 4);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (83, 'Dodge', 'Ram 3500', 2019, 'Diesel', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (84, 'Chrysler', 'PT Cruiser', 2022, 'Electric', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (85, 'Dodge', 'Intrepid', 2022, 'Diesel', 'CVT', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (86, 'Mazda', '929', 2020, 'Electric', 'CVT', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (87, 'Volkswagen', 'Type 2', 2019, 'Diesel', 'CVT', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (88, 'Honda', 'Prelude', 2019, 'Electric', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (89, 'Mercedes-Benz', 'C-Class', 2020, 'Gasoline', 'Automatic', 2);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (90, 'Cadillac', 'Escalade ESV', 2020, 'Electric', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (91, 'Subaru', 'Outback', 2020, 'Gasoline', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (92, 'Buick', 'Regal', 2022, 'Diesel', 'Automatic', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (93, 'Ford', 'Explorer Sport', 2018, 'Electric', 'Automatic', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (94, 'Audi', 'Q7', 2020, 'Electric', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (95, 'Volkswagen', 'GTI', 2022, 'Electric', 'Automatic', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (96, 'Suzuki', 'Swift', 2019, 'Electric', 'Manual', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (97, 'Chevrolet', 'Venture', 2018, 'Gasoline', 'CVT', 3);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (98, 'Chevrolet', 'Express 2500', 2018, 'Gasoline', 'Automatic', 5);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (99, 'Hyundai', 'Tucson', 2019, 'Diesel', 'Manual', 1);
insert into cars (id, make, model, year, fuel_type, transmission, owners) values (100, 'Audi', 'TT', 2018, 'Gasoline', 'Automatic', 2);
